# Generated by Django 5.1.3 on 2024-11-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
